import type { Slot, Alert, WaitlistEntry } from "./types";

export const workspaceName = "Radiology Group Vienna";

export const initialSlots: Slot[] = [
  {
    id: "s-1030",
    timeLabel: "10:30",
    startsInMin: 12,
    provider: "Dr. Weber",
    service: "CT Scan",
    status: "OFFERING",
    fillMode: "Balanced",
    waveSize: 3,
    attempts: 4,
    attemptsTotal: 6,
    lastEvent: "Wave widened to 3",
    needsAttention: true,
    reasoning:
      "Wave widened to 3 because only 18 minutes remained when last wave completed without acceptance.",
    qualitative: { responseRate: "Normal", fillConfidence: "Under target" },
    activeWave: {
      number: 3,
      size: 3,
      timeoutSec: 42,
      candidates: [
        { name: "Anna Berger", state: "ringing" },
        { name: "Tobias Lang", state: "ringing" },
        { name: "Sophie Huber", state: "no_answer" },
      ],
    },
    timeline: [
      { id: "e1", at: "09:48", kind: "slot_opened", message: "Slot opened (cancellation)" },
      {
        id: "e2",
        at: "09:48",
        kind: "ranking",
        message: "Ranked Maria Schmidt first — matches Tuesday AM preference, waited 21 days",
      },
      { id: "e3", at: "09:49", kind: "wave_dispatched", message: "Wave 1 dispatched (size 1)" },
      { id: "e4", at: "09:52", kind: "call_outcome", message: "Maria Schmidt — no answer" },
      { id: "e5", at: "10:04", kind: "wave_dispatched", message: "Wave 2 dispatched (size 1)" },
      { id: "e6", at: "10:09", kind: "call_outcome", message: "Lukas Mayr — declined" },
      {
        id: "e7",
        at: "10:12",
        kind: "wave_widened",
        message: "Wave widened to 3 because only 18 minutes remain",
      },
      { id: "e8", at: "10:12", kind: "wave_dispatched", message: "Wave 3 dispatched (size 3)" },
    ],
    candidates: [
      {
        id: "c1",
        rank: 1,
        name: "Anna Berger",
        matchReason: "Matches Tuesday AM preference, high acceptance likelihood",
        waitDays: 14,
        contactStatus: "ringing",
        eligible: true,
        lastContacted: "now",
      },
      {
        id: "c2",
        rank: 2,
        name: "Tobias Lang",
        matchReason: "Waited 19 days, prefers morning",
        waitDays: 19,
        contactStatus: "ringing",
        eligible: true,
        lastContacted: "now",
      },
      {
        id: "c3",
        rank: 3,
        name: "Sophie Huber",
        matchReason: "Provider preference match",
        waitDays: 8,
        contactStatus: "no_answer",
        eligible: true,
        lastContacted: "1 min ago",
      },
      {
        id: "c4",
        rank: 4,
        name: "Klara Fuchs",
        matchReason: "Skipped: contacted twice this week",
        waitDays: 22,
        contactStatus: "skipped",
        eligible: false,
        lastContacted: "2 days ago",
        skipReason: "Contact limit reached this week",
      },
      {
        id: "c5",
        rank: 5,
        name: "Markus Wolf",
        matchReason: "Skipped: quiet hours conflict resolved",
        waitDays: 11,
        contactStatus: "not_contacted",
        eligible: true,
        lastContacted: null,
      },
    ],
  },
  {
    id: "s-1100",
    timeLabel: "11:00",
    startsInMin: 42,
    provider: "Dr. Klein",
    service: "Consultation",
    status: "ESCALATED",
    fillMode: "Balanced",
    waveSize: 0,
    attempts: 0,
    attemptsTotal: 0,
    lastEvent: "No eligible candidates",
    needsAttention: true,
    reasoning:
      "Automatic filling stopped: no waitlist candidates match this service + provider with active consent.",
    qualitative: { responseRate: "—", fillConfidence: "No candidates" },
    timeline: [
      { id: "e1", at: "10:18", kind: "slot_opened", message: "Slot opened (no-show)" },
      {
        id: "e2",
        at: "10:18",
        kind: "escalated",
        message: "Escalated to receptionist: no eligible candidates",
      },
    ],
    candidates: [],
  },
  {
    id: "s-1130",
    timeLabel: "11:30",
    startsInMin: 72,
    provider: "Dr. Weber",
    service: "CT Scan",
    status: "BOOKED",
    fillMode: "Balanced",
    waveSize: 2,
    attempts: 3,
    attemptsTotal: 3,
    lastEvent: "Booked Maria Schmidt",
    needsAttention: false,
    bookedCustomer: "Maria Schmidt",
    recoveredMinBeforeStart: 42,
    reasoning:
      "Slot booked. Maria accepted first in wave 2. Jonas also accepted and received runner-up priority for the next eligible matching opening.",
    qualitative: { responseRate: "Normal", fillConfidence: "Met" },
    timeline: [
      { id: "e1", at: "08:30", kind: "slot_opened", message: "Slot opened (reschedule request)" },
      { id: "e2", at: "08:30", kind: "ranking", message: "Ranked Maria Schmidt first" },
      { id: "e3", at: "08:31", kind: "wave_dispatched", message: "Wave 1 dispatched (size 1)" },
      { id: "e4", at: "08:36", kind: "call_outcome", message: "Maria Schmidt — no answer" },
      { id: "e5", at: "10:35", kind: "wave_dispatched", message: "Wave 2 dispatched (size 2)" },
      { id: "e6", at: "10:38", kind: "call_outcome", message: "Maria Schmidt — accepted" },
      { id: "e7", at: "10:38", kind: "call_outcome", message: "Jonas Pirker — accepted" },
      { id: "e8", at: "10:38", kind: "booked", message: "Maria Schmidt booked the slot" },
      {
        id: "e9",
        at: "10:38",
        kind: "runner_up",
        message: "Jonas Pirker received runner-up priority for next eligible matching slot",
      },
    ],
    candidates: [
      {
        id: "c1",
        rank: 1,
        name: "Maria Schmidt",
        matchReason: "Won — accepted first in wave 2",
        waitDays: 21,
        contactStatus: "booked",
        eligible: true,
        lastContacted: "10:38",
      },
      {
        id: "c2",
        rank: 2,
        name: "Jonas Pirker",
        matchReason: "Accepted in same wave — runner-up priority granted",
        waitDays: 16,
        contactStatus: "runner_up",
        eligible: true,
        lastContacted: "10:38",
      },
    ],
    runnerUp: {
      winner: "Maria Schmidt",
      runnerUps: [
        { name: "Jonas Pirker", messageStatus: "Runner-up SMS delivered", priorityActive: true },
      ],
      note: "Jonas also accepted after Maria. Maria won the slot. Jonas received priority for the next eligible matching opening.",
    },
  },
  {
    id: "s-1200",
    timeLabel: "12:00",
    startsInMin: 135,
    provider: "Dr. Novak",
    service: "Follow-up",
    status: "OPEN",
    fillMode: "Patient",
    waveSize: 1,
    attempts: 1,
    attemptsTotal: 4,
    lastEvent: "Next call queued",
    needsAttention: false,
    reasoning:
      "Calling one at a time because there is enough runway (2h 15m). Next wave will dispatch when the current candidate times out.",
    qualitative: { responseRate: "Normal", fillConfidence: "On track" },
    activeWave: {
      number: 1,
      size: 1,
      timeoutSec: 95,
      candidates: [{ name: "Eva Reiter", state: "ringing" }],
    },
    timeline: [
      { id: "e1", at: "09:45", kind: "slot_opened", message: "Slot opened (cancellation)" },
      {
        id: "e2",
        at: "09:45",
        kind: "ranking",
        message: "Ranked Eva Reiter first — matches midday preference, waited 18 days",
      },
      { id: "e3", at: "09:46", kind: "wave_dispatched", message: "Wave 1 dispatched (size 1)" },
    ],
    candidates: [
      {
        id: "c1",
        rank: 1,
        name: "Eva Reiter",
        matchReason: "Matches midday preference, waited 18 days",
        waitDays: 18,
        contactStatus: "ringing",
        eligible: true,
        lastContacted: "now",
      },
      {
        id: "c2",
        rank: 2,
        name: "Daniel Brunner",
        matchReason: "Provider preference match",
        waitDays: 12,
        contactStatus: "not_contacted",
        eligible: true,
        lastContacted: null,
      },
      {
        id: "c3",
        rank: 3,
        name: "Linda Vogel",
        matchReason: "High acceptance likelihood",
        waitDays: 9,
        contactStatus: "not_contacted",
        eligible: true,
        lastContacted: null,
      },
    ],
  },
  {
    id: "s-1330",
    timeLabel: "13:30",
    startsInMin: 225,
    provider: "Dr. Weber",
    service: "CT Scan",
    status: "OPEN",
    fillMode: "Balanced",
    waveSize: 1,
    attempts: 0,
    attemptsTotal: 4,
    lastEvent: "Ranking complete",
    needsAttention: false,
    reasoning:
      "Calling one at a time because there is enough runway. Jonas Pirker ranked first due to runner-up priority from earlier accepted slot and eligibility for this opening.",
    qualitative: { responseRate: "Normal", fillConfidence: "On track" },
    timeline: [
      { id: "e1", at: "10:40", kind: "slot_opened", message: "Slot opened (cancellation)" },
      {
        id: "e2",
        at: "10:40",
        kind: "ranking",
        message:
          "Ranked Jonas Pirker first — runner-up priority from previous accepted slot, eligible for this opening",
      },
    ],
    candidates: [
      {
        id: "c1",
        rank: 1,
        name: "Jonas Pirker",
        matchReason: "Runner-up priority from previous accepted slot, eligible for this opening",
        waitDays: 16,
        contactStatus: "not_contacted",
        eligible: true,
        lastContacted: "10:38",
        runnerUpBoost: true,
      },
      {
        id: "c2",
        rank: 2,
        name: "Anna Berger",
        matchReason: "Matches Tuesday afternoon preference",
        waitDays: 14,
        contactStatus: "not_contacted",
        eligible: true,
        lastContacted: null,
      },
    ],
  },
  {
    id: "s-1400",
    timeLabel: "14:00",
    startsInMin: 255,
    provider: "Dr. Klein",
    service: "Consultation",
    status: "OPEN",
    fillMode: "Balanced",
    waveSize: 1,
    attempts: 0,
    attemptsTotal: 4,
    lastEvent: "Awaiting first wave",
    needsAttention: false,
    reasoning: "Calling one at a time because there is enough runway.",
    qualitative: { responseRate: "Normal", fillConfidence: "On track" },
    timeline: [
      { id: "e1", at: "10:55", kind: "slot_opened", message: "Slot opened (cancellation)" },
    ],
    candidates: [
      {
        id: "c1",
        rank: 1,
        name: "Helga Stein",
        matchReason: "Matches Tuesday afternoon preference",
        waitDays: 25,
        contactStatus: "not_contacted",
        eligible: true,
        lastContacted: null,
      },
    ],
  },
];

export const initialAlerts: Alert[] = [
  {
    id: "a1",
    severity: "danger",
    slotId: "s-1030",
    title: "10:30 CT Scan expires in 12 min",
    reason: "Wave widened to 3. No acceptance yet.",
    primaryAction: "Review",
    actionKind: "review",
  },
  {
    id: "a2",
    severity: "danger",
    slotId: "s-1100",
    title: "11:00 Consultation has no eligible candidates",
    reason: "Escalated to receptionist for manual outreach.",
    primaryAction: "Open slot",
    actionKind: "open",
  },
  {
    id: "a3",
    severity: "warning",
    slotId: "s-1130",
    title: "Double accept on 11:30 CT Scan",
    reason: "Maria booked, Jonas became runner-up.",
    primaryAction: "Review",
    actionKind: "review",
  },
  {
    id: "a4",
    severity: "info",
    title: "Provider webhook latency elevated",
    reason: "Calendar sync delays of 4–6s observed in the last 10 min.",
    primaryAction: "Review",
    actionKind: "review",
  },
];

export const initialWaitlist: WaitlistEntry[] = [
  {
    id: "w1",
    name: "Maria Schmidt",
    phone: "+34612345671",
    preferredTimes: "Tue/Thu mornings",
    serviceTypes: ["CT Scan", "MRI"],
    waitDays: 21,
    contactsThisWeek: 1,
    contactLimitPerWeek: 2,
    consent: "granted",
    lastContacted: "Today 10:38",
    eligibilityNotes: "All providers",
    status: "active",
    recentContacts: [
      { at: "Today 10:38", outcome: "booked", slot: "11:30 CT Scan" },
      { at: "Today 08:36", outcome: "no_answer", slot: "11:30 CT Scan" },
    ],
    upcomingMatches: ["Tue 09:00 CT Scan", "Thu 10:00 MRI"],
  },
  {
    id: "w2",
    name: "Jonas Pirker",
    phone: "+34612345672",
    preferredTimes: "Weekday afternoons",
    serviceTypes: ["CT Scan"],
    waitDays: 16,
    contactsThisWeek: 1,
    contactLimitPerWeek: 2,
    consent: "granted",
    lastContacted: "Today 10:38",
    priorityBoost: "Runner-up priority — expires in 6 days",
    eligibilityNotes: "All providers",
    status: "active",
    recentContacts: [{ at: "Today 10:38", outcome: "runner_up", slot: "11:30 CT Scan" }],
    runnerUpHistory: [
      { at: "Today 10:38", slot: "11:30 CT Scan", reason: "Accepted after Maria in same wave" },
    ],
    upcomingMatches: ["Today 13:30 CT Scan", "Tomorrow 14:00 CT Scan"],
  },
  {
    id: "w3",
    name: "Anna Berger",
    phone: "+34612345673",
    preferredTimes: "Tuesday mornings",
    serviceTypes: ["CT Scan"],
    waitDays: 14,
    contactsThisWeek: 1,
    contactLimitPerWeek: 2,
    consent: "granted",
    lastContacted: "Today 10:12",
    eligibilityNotes: "Dr. Weber preferred",
    status: "active",
  },
  {
    id: "w4",
    name: "Tobias Lang",
    phone: "+34612345674",
    preferredTimes: "Mornings",
    serviceTypes: ["CT Scan", "X-Ray"],
    waitDays: 19,
    contactsThisWeek: 1,
    contactLimitPerWeek: 2,
    consent: "granted",
    lastContacted: "Today 10:12",
    eligibilityNotes: "All providers",
    status: "active",
  },
  {
    id: "w5",
    name: "Klara Fuchs",
    phone: "+34612345675",
    preferredTimes: "Anytime",
    serviceTypes: ["CT Scan"],
    waitDays: 22,
    contactsThisWeek: 2,
    contactLimitPerWeek: 2,
    consent: "granted",
    lastContacted: "Yesterday 16:20",
    eligibilityNotes: "Contact limit reached this week",
    status: "snoozed",
  },
  {
    id: "w6",
    name: "Eva Reiter",
    phone: "+34612345676",
    preferredTimes: "Midday",
    serviceTypes: ["Follow-up", "Consultation"],
    waitDays: 18,
    contactsThisWeek: 1,
    contactLimitPerWeek: 3,
    consent: "granted",
    lastContacted: "Today 09:46",
    eligibilityNotes: "All providers",
    status: "active",
  },
  {
    id: "w7",
    name: "Helga Stein",
    phone: "+34612345677",
    preferredTimes: "Tue/Wed afternoons",
    serviceTypes: ["Consultation"],
    waitDays: 25,
    contactsThisWeek: 0,
    contactLimitPerWeek: 2,
    consent: "granted",
    lastContacted: null,
    priorityBoost: "VIP",
    eligibilityNotes: "All providers",
    status: "active",
  },
  {
    id: "w8",
    name: "Daniel Brunner",
    phone: "+34612345678",
    preferredTimes: "Late morning",
    serviceTypes: ["Follow-up"],
    waitDays: 12,
    contactsThisWeek: 0,
    contactLimitPerWeek: 2,
    consent: "granted",
    lastContacted: null,
    eligibilityNotes: "Dr. Novak preferred",
    status: "active",
  },
  {
    id: "w9",
    name: "Markus Wolf",
    phone: "+34612345679",
    preferredTimes: "Mornings",
    serviceTypes: ["CT Scan"],
    waitDays: 11,
    contactsThisWeek: 0,
    contactLimitPerWeek: 2,
    consent: "pending",
    lastContacted: null,
    eligibilityNotes: "Awaiting consent confirmation",
    status: "paused",
  },
];

export const analyticsData = {
  metrics: [
    { label: "Slots recovered", value: "184", delta: "+12% vs last week" },
    { label: "Fill rate", value: "78%", delta: "+4 pts" },
    { label: "Average time to fill", value: "37 min", delta: "−8 min" },
    { label: "Revenue protected (est.)", value: "€48,200", delta: "+€5,100" },
    { label: "No-answer rate", value: "31%", delta: "−2 pts" },
    { label: "Decline rate", value: "18%", delta: "flat" },
    { label: "Avg contacts per recovered slot", value: "2.4", delta: "−0.3" },
    { label: "Runner-up priority honored", value: "92%", delta: "+1 pt" },
  ],
  fillRateOverTime: [
    { day: "Mon", rate: 71 },
    { day: "Tue", rate: 74 },
    { day: "Wed", rate: 69 },
    { day: "Thu", rate: 78 },
    { day: "Fri", rate: 82 },
    { day: "Sat", rate: 76 },
    { day: "Sun", rate: 80 },
  ],
  recoveredByProvider: [
    { provider: "Dr. Weber", count: 64 },
    { provider: "Dr. Klein", count: 41 },
    { provider: "Dr. Novak", count: 52 },
    { provider: "Dr. Hahn", count: 27 },
  ],
  declineReasons: [
    { reason: "Time conflict", count: 38 },
    { reason: "No longer needed", count: 21 },
    { reason: "Wants different provider", count: 12 },
    { reason: "Other", count: 9 },
  ],
  contactVolumeByDay: [
    { day: "Mon", calls: 120 },
    { day: "Tue", calls: 142 },
    { day: "Wed", calls: 131 },
    { day: "Thu", calls: 158 },
    { day: "Fri", calls: 171 },
    { day: "Sat", calls: 88 },
    { day: "Sun", calls: 62 },
  ],
  escalationsByReason: [
    { reason: "No eligible candidates", count: 11 },
    { reason: "Provider webhook error", count: 4 },
    { reason: "Manual booking conflict", count: 3 },
    { reason: "Consent expired", count: 2 },
  ],
  insights: [
    "Most recovered slots came from customers with saved time preferences.",
    "Escalations increased when fewer eligible candidates were available.",
    "Runner-up priority converted 92% of follow-up offers within 7 days.",
  ],
};
